TEST = "Test"
PROD = "Prod"
TESTURL = "https://test.bitpay.com/"
PRODURL = "https://bitpay.com/"
BITPAYAPIVERSION = "2.0.0"
BITPAYPLUGININFO = "BitPay_Python_Client_v6.0.2111"
BITPAYAPIFRAME = "std"
BITPAYAPIFRAMEVERSION = "1.0.0"
