on:
  release:
    types:
      - published

name: release

jobs:
  package:
    name: Package release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          pip3 install --upgrade build
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist

  pypi-publish:
    needs: ['package']
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: artifact/

  readme-changelog:
    name: Publish changelog to Readme
    needs: ['pypi-publish']
    runs-on: ubuntu-latest
    steps:
      - name: Extract release data
        id: release
        env:
          RELEASE_NAME: ${{ github.event.release.name }}
          RELEASE_BODY: ${{ github.event.release.body }}
        run: |
          echo "title=$RELEASE_NAME" >> $GITHUB_OUTPUT
          {
            echo "body<<EOF"
            echo "$RELEASE_BODY"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Publish changelog to Readme
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
          RELEASE_TITLE: ${{ steps.release.outputs.title }}
          RELEASE_BODY: ${{ steps.release.outputs.body }}
        run: |
          jq -n --arg title "Python Unified SDK $RELEASE_TITLE" \
                --arg body "$RELEASE_BODY" \
                '{
                  title: $title,
                  content: {
                    body: $body
                  },
                  privacy: { view: "public" }
                }' > payload.json

          curl --location 'https://api.readme.com/v2/changelogs' \
            --header "Authorization: Bearer $README_API_KEY" \
            --header 'Content-Type: application/json' \
            --data @payload.json
