on:
  release:
    types:
      - published

name: release

jobs:
  package:
    name: Package release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: |
          python setup.py sdist
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist

  pypi-publish:
    needs: ['package']
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: artifact/